[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "nodejs_20"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader", "npm install", "npm run build"]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
PHP_VERSION = "8.4"
NODE_VERSION = "20"
